### PR TITLE
Display package versions in descending instead of ascending order

### PR DESCRIPTION
**Pull request by ddzz**
Before:
Screen Shot 2021-09-08 at 6 46 44 PM

After:
Screen Shot 2021-09-08 at 6 47 04 PM

### CODE REVIEW

**Comment by bmish** [comment]
I need some convincing (maybe an example) about why descending order would be more intuitive than ascending order here.

**Comment by ddzz** [comment]
> I need some convincing (maybe an example) about why descending order would be more intuitive than ascending order here.

In many cases (probably most cases) the most recent version will be used to resolve an inconsistency, so it makes sense to show the most relevant version first.

**Comment by bmish** [comment]
I'll consider this in the coming days. The README would need to be updated to go along with this if accepted.

**Comment by bmish** [comment]
@ddzz I'm ready to accept this, please rebase and update tests/docs.

**Comment by ddzz** [comment]
@bmish PR has been updated.

**Review by bmish — APPROVED** [review]
Thank you!

**Pull request merged**
