### PR TITLE
Refactor CI workflow

### PR DESCRIPTION
**Pull request by ddzz**

### CODE REVIEW

**Comment by bmish** [comment]
Why? I don't really mind if CI fails fast.

**Comment by ddzz** [comment]
> Why? I don't really mind if CI fails fast.

You are more likely to catch multiple issues when fail fast is disabled.

**Comment by bmish** [comment]
We have 6 build checks (different versions of Node and Linux vs. Windows). They pretty much all have the same output. It's pretty rare that you'll hit one failure in one check and then a separate failure in another check. So I think it would be wasteful to continue running all checks after a failure.

**Comment by ddzz** [comment]
> We have 6 build checks (different versions of Node and Linux vs. Windows). They pretty much all have the same output. It's pretty rare that you'll hit one failure in one check and then a separate failure in another check. So I think it would be wasteful to continue running all checks after a failure.

Good points. I just refactored the workflow here so that tests only run on Node 14.x first. If those pass all other versions run. This slows down CI somewhat, but it's not as wasteful when there's a failure.

**Comment by bmish** [comment]
Not a fan of having all the steps duplicated as it would be easy for those to get out-of-sync later. 

Right now, we're just using the default CI workflow from Github, which I'm inclined to stick with, as I'm not clear what problems this is addressing.

**Comment by ddzz** [comment]
> Not a fan of having all the steps duplicated as it would be easy for those to get out-of-sync later.
> 
> Right now, we're just using the default CI workflow from Github, which I'm inclined to stick with, as I'm not clear what problems this is addressing.

This workflow uses fewer resources when there's a failure on CI.

**Comment by bmish** [comment]
> This workflow uses fewer resources when there's a failure on CI.

That's true but I don't think it's worth the added complexity to our CI configuration. CI is extremely lightweight and fast for this repository so it seems like an unnecessary optimization.

**Pull request closed without merging**
